version: '3.3'

services:
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - mysql_db:/var/lib/mysql
      - ./backend/database:/docker-entrypoint-initdb.d
    networks:
      - my-network
  python_app:
    build: .
    restart: always
    depends_on:
      - mysql_db
    networks:
      - my-network


volumes:
  mysql_db:

networks:
  my-network:
